version: "3"
services:
  db:
    image: postgres
    restart:
      always
    environment:
      POSTGRES_USER: client
      POSTGRES_DB: bmw_pilot
      POSTGRES_PASSWORD: qwer1234
    volumes:
      - postgres_data:/var/lib/posgresql/data
  app:
    build:
      context: .
    restart:
      always
    environment:
      POSTGRES_USER: client
      POSTGRES_DB: bmw_pilot
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./zuri:/zuri
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  postgres_data:
